# Use the latest LTS version of Node.js
FROM node:18-alpine

WORKDIR /usr/src/app
EXPOSE 3001

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev
USER node
COPY . .
CMD npm run dev